/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkg1;

/**
 *
 * @author LDS
 */
public class proyecto extends javax.swing.JFrame {

    /**
     * Creates new form proyecto
     */
    public proyecto() {
        initComponents();
        AreaCirculo.setVisible(false);
        AreaCuadrado.setVisible(false);
        AreaRectangulo.setVisible(false);
        hipotenusa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        AreaCuadrado = new javax.swing.JPanel();
        jTextFieldCuadrado = new javax.swing.JTextField();
        CalcularCuadrado = new javax.swing.JButton();
        jLabelCuadrado = new javax.swing.JLabel();
        AreaCirculo = new javax.swing.JPanel();
        jTextFieldCirculo = new javax.swing.JTextField();
        CalcularCirculo = new javax.swing.JButton();
        jLabelCirculo = new javax.swing.JLabel();
        AreaRectangulo = new javax.swing.JPanel();
        jTextFieldRectanguloBase = new javax.swing.JTextField();
        CalcularRectangulo = new javax.swing.JButton();
        jTextFieldRectanguloAltura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRectangulo = new javax.swing.JLabel();
        hipotenusa = new javax.swing.JPanel();
        jTextFieldCatetoX = new javax.swing.JTextField();
        CalcularHipotenusa = new javax.swing.JButton();
        jTextFieldCatetoY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelHipotenusa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Áreas = new javax.swing.JMenu();
        Circulo = new javax.swing.JMenuItem();
        Cuadrado = new javax.swing.JMenuItem();
        Rectangulo = new javax.swing.JMenuItem();
        Hipotenusa = new javax.swing.JMenu();
        hipot = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaCuadrado.setBorder(javax.swing.BorderFactory.createTitledBorder("Área de cuadrado"));

        CalcularCuadrado.setText("Calcular");
        CalcularCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularCuadradoActionPerformed(evt);
            }
        });

        jLabelCuadrado.setText("Área de Cuadrado es...");

        javax.swing.GroupLayout AreaCuadradoLayout = new javax.swing.GroupLayout(AreaCuadrado);
        AreaCuadrado.setLayout(AreaCuadradoLayout);
        AreaCuadradoLayout.setHorizontalGroup(
            AreaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCuadradoLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jTextFieldCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(AreaCuadradoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(CalcularCuadrado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AreaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AreaCuadradoLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabelCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(75, 75, 75)))
        );
        AreaCuadradoLayout.setVerticalGroup(
            AreaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCuadradoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTextFieldCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(CalcularCuadrado)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(AreaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AreaCuadradoLayout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(jLabelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        AreaCirculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Área de circulo"));

        CalcularCirculo.setText("Calcular");
        CalcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreaCirculoLayout = new javax.swing.GroupLayout(AreaCirculo);
        AreaCirculo.setLayout(AreaCirculoLayout);
        AreaCirculoLayout.setHorizontalGroup(
            AreaCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaCirculoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(CalcularCirculo)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCirculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AreaCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        AreaCirculoLayout.setVerticalGroup(
            AreaCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCirculoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTextFieldCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CalcularCirculo)
                .addGap(76, 76, 76)
                .addComponent(jLabelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        AreaRectangulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Área de rectangulo"));

        CalcularRectangulo.setText("Calcular");
        CalcularRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularRectanguloActionPerformed(evt);
            }
        });

        jLabel1.setText("Base");

        jLabel2.setText("Altura");

        javax.swing.GroupLayout AreaRectanguloLayout = new javax.swing.GroupLayout(AreaRectangulo);
        AreaRectangulo.setLayout(AreaRectanguloLayout);
        AreaRectanguloLayout.setHorizontalGroup(
            AreaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaRectanguloLayout.createSequentialGroup()
                .addGroup(AreaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaRectanguloLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(CalcularRectangulo))
                    .addGroup(AreaRectanguloLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(AreaRectanguloLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaRectanguloLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(AreaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldRectanguloAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jTextFieldRectanguloBase, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabelRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        AreaRectanguloLayout.setVerticalGroup(
            AreaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaRectanguloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRectanguloBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRectanguloAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(CalcularRectangulo)
                .addGap(57, 57, 57)
                .addComponent(jLabelRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        hipotenusa.setBorder(javax.swing.BorderFactory.createTitledBorder("Hipotenusa"));

        CalcularHipotenusa.setText("Calcular");
        CalcularHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularHipotenusaActionPerformed(evt);
            }
        });

        jLabel3.setText("Cateto X");

        jLabel4.setText("Cateto Y");

        javax.swing.GroupLayout hipotenusaLayout = new javax.swing.GroupLayout(hipotenusa);
        hipotenusa.setLayout(hipotenusaLayout);
        hipotenusaLayout.setHorizontalGroup(
            hipotenusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hipotenusaLayout.createSequentialGroup()
                .addGroup(hipotenusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hipotenusaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(CalcularHipotenusa))
                    .addGroup(hipotenusaLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3))
                    .addGroup(hipotenusaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hipotenusaLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(hipotenusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCatetoY, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jTextFieldCatetoX, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabelHipotenusa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        hipotenusaLayout.setVerticalGroup(
            hipotenusaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hipotenusaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCatetoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCatetoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CalcularHipotenusa)
                .addGap(53, 53, 53)
                .addComponent(jLabelHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(AreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(AreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(AreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(AreaCuadrado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AreaCirculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AreaRectangulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hipotenusa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Áreas.setText("Áreas");

        Circulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Circulo.setText(" Área del círculo");
        Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoActionPerformed(evt);
            }
        });
        Áreas.add(Circulo);

        Cuadrado.setText("Área del cuadrado ");
        Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadradoActionPerformed(evt);
            }
        });
        Áreas.add(Cuadrado);

        Rectangulo.setText("Área del rectángulo");
        Rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectanguloActionPerformed(evt);
            }
        });
        Áreas.add(Rectangulo);

        jMenuBar1.add(Áreas);

        Hipotenusa.setText("Hipotenusa");

        hipot.setText("Hipotenusa");
        hipot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hipotActionPerformed(evt);
            }
        });
        Hipotenusa.add(hipot);

        jMenuBar1.add(Hipotenusa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoActionPerformed
        AreaCirculo.setVisible(true);
        AreaCuadrado.setVisible(false);
        AreaRectangulo.setVisible(false);
        hipotenusa.setVisible(false);
    }//GEN-LAST:event_CirculoActionPerformed

    private void CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadradoActionPerformed
        AreaCuadrado.setVisible(true);
        AreaCirculo.setVisible(false);
        AreaRectangulo.setVisible(false);
        hipotenusa.setVisible(false);
    }//GEN-LAST:event_CuadradoActionPerformed

    private void RectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectanguloActionPerformed

        AreaRectangulo.setVisible(true);
        AreaCuadrado.setVisible(false);
        AreaCirculo.setVisible(false);
        hipotenusa.setVisible(false);
    }//GEN-LAST:event_RectanguloActionPerformed

    private void hipotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hipotActionPerformed
        hipotenusa.setVisible(true);
        AreaRectangulo.setVisible(false);
        AreaCuadrado.setVisible(false);
        AreaCirculo.setVisible(false);
    }//GEN-LAST:event_hipotActionPerformed

    private void CalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularCirculoActionPerformed
        double radio = Double.valueOf(jTextFieldCirculo.getText());
        Circulo circulo = new Circulo(radio);
        circulo.area();
        String area = String.valueOf(circulo.getAreaRadio());
        jLabelCirculo.setText("Área del círculo de radio " + radio + " = " + area);
    }//GEN-LAST:event_CalcularCirculoActionPerformed

    private void CalcularCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularCuadradoActionPerformed
        double lado = Double.valueOf(jTextFieldCuadrado.getText());
        Cuadrado cuadrado = new Cuadrado(lado);
        cuadrado.area();
        String area = String.valueOf(cuadrado.getareaCuadrado());
        jLabelCuadrado.setText("Área del cuadrado de lado " + lado + " = " + area);
    }//GEN-LAST:event_CalcularCuadradoActionPerformed

    private void CalcularRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularRectanguloActionPerformed
        double base = Double.valueOf(jTextFieldRectanguloBase.getText());
        double altura = Double.valueOf(jTextFieldRectanguloAltura.getText());
        Rectangulo rectangulo = new Rectangulo(base, altura);
        rectangulo.area();
        String area = String.valueOf(rectangulo.getAreaRectangulo());
        jLabelRectangulo.setText("Área del rectángulo de base " + base + " y altura " + altura + " = " + area);
    }//GEN-LAST:event_CalcularRectanguloActionPerformed

    private void CalcularHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularHipotenusaActionPerformed
        double catetoX = Double.valueOf(jTextFieldCatetoX.getText());
        double catetoY = Double.valueOf(jTextFieldCatetoY.getText());
        Hipotenusa hipotenusa = new Hipotenusa(catetoX, catetoY);
        hipotenusa.hipotenusa();
        String hipo = String.valueOf(hipotenusa.getHipotenusa());
        jLabelHipotenusa.setText("La hipotenusa de cateto X " + catetoX + " y cateto Y  " + catetoY + " = " + hipo);
    }//GEN-LAST:event_CalcularHipotenusaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaCirculo;
    private javax.swing.JPanel AreaCuadrado;
    private javax.swing.JPanel AreaRectangulo;
    private javax.swing.JButton CalcularCirculo;
    private javax.swing.JButton CalcularCuadrado;
    private javax.swing.JButton CalcularHipotenusa;
    private javax.swing.JButton CalcularRectangulo;
    private javax.swing.JMenuItem Circulo;
    private javax.swing.JMenuItem Cuadrado;
    private javax.swing.JMenu Hipotenusa;
    private javax.swing.JMenuItem Rectangulo;
    private javax.swing.JMenuItem hipot;
    private javax.swing.JPanel hipotenusa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCirculo;
    private javax.swing.JLabel jLabelCuadrado;
    private javax.swing.JLabel jLabelHipotenusa;
    private javax.swing.JLabel jLabelRectangulo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextFieldCatetoX;
    private javax.swing.JTextField jTextFieldCatetoY;
    private javax.swing.JTextField jTextFieldCirculo;
    private javax.swing.JTextField jTextFieldCuadrado;
    private javax.swing.JTextField jTextFieldRectanguloAltura;
    private javax.swing.JTextField jTextFieldRectanguloBase;
    private javax.swing.JMenu Áreas;
    // End of variables declaration//GEN-END:variables
}
